apiVersion: v1
kind: Secret
metadata:
  name: blinky-core-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: "_openai_api_key_"
  TWILIO_ACCOUNT_SID: "_tu_twilio_sid_"
  TWILIO_AUTH_TOKEN: "_tu_twilio_token_"
  TWILIO_WHATSAPP_FROM: "_whatsapp:_"
